#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-scikit_image
Version  : 0.20.0
Release  : 83
URL      : https://files.pythonhosted.org/packages/03/55/0ff6e41c39c64d9ad18bf31c953c28f525533609c7371fa2790558ca8197/scikit_image-0.20.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/03/55/0ff6e41c39c64d9ad18bf31c953c28f525533609c7371fa2790558ca8197/scikit_image-0.20.0.tar.gz
Summary  : Image processing in Python
Group    : Development/Tools
License  : * MIT
Requires: pypi-scikit_image-filemap = %{version}-%{release}
Requires: pypi-scikit_image-lib = %{version}-%{release}
Requires: pypi-scikit_image-license = %{version}-%{release}
Requires: pypi-scikit_image-python = %{version}-%{release}
Requires: pypi-scikit_image-python3 = %{version}-%{release}
Requires: pypi(cloudpickle)
Requires: pypi(dask)
Requires: pypi(imageio)
Requires: pypi(matplotlib)
Requires: pypi(networkx)
Requires: pypi(pillow)
Requires: pypi(pywavelets)
Requires: pypi(scipy)
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-meson
BuildRequires : pypi(cython)
BuildRequires : pypi(dask)
BuildRequires : pypi(lazy_loader)
BuildRequires : pypi(meson_python)
BuildRequires : pypi(networkx)
BuildRequires : pypi(numpy)
BuildRequires : pypi(packaging)
BuildRequires : pypi(pillow)
BuildRequires : pypi(pythran)
BuildRequires : pypi(pywavelets)
BuildRequires : pypi(scikit_learn)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-cython
BuildRequires : pypi-pythran
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# scikit-image: Image processing in Python
[![Image.sc forum](https://img.shields.io/badge/dynamic/json.svg?label=forum&url=https%3A%2F%2Fforum.image.sc%2Ftags%2Fscikit-image.json&query=%24.topic_list.tags.0.topic_count&colorB=brightgreen&suffix=%20topics&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAABPklEQVR42m3SyyqFURTA8Y2BER0TDyExZ+aSPIKUlPIITFzKeQWXwhBlQrmFgUzMMFLKZeguBu5y+//17dP3nc5vuPdee6299gohUYYaDGOyyACq4JmQVoFujOMR77hNfOAGM+hBOQqB9TjHD36xhAa04RCuuXeKOvwHVWIKL9jCK2bRiV284QgL8MwEjAneeo9VNOEaBhzALGtoRy02cIcWhE34jj5YxgW+E5Z4iTPkMYpPLCNY3hdOYEfNbKYdmNngZ1jyEzw7h7AIb3fRTQ95OAZ6yQpGYHMMtOTgouktYwxuXsHgWLLl+4x++Kx1FJrjLTagA77bTPvYgw1rRqY56e+w7GNYsqX6JfPwi7aR+Y5SA+BXtKIRfkfJAYgj14tpOF6+I46c4/cAM3UhM3JxyKsxiOIhH0IO6SH/A1Kb1WBeUjbkAAAAAElFTkSuQmCC)](https://forum.image.sc/tags/scikit-image)
[![Stackoverflow](https://img.shields.io/badge/stackoverflow-Ask%20questions-blue.svg)](https://stackoverflow.com/questions/tagged/scikit-image)
[![project chat](https://img.shields.io/badge/zulip-join_chat-brightgreen.svg)](https://skimage.zulipchat.com)

%package filemap
Summary: filemap components for the pypi-scikit_image package.
Group: Default

%description filemap
filemap components for the pypi-scikit_image package.


%package lib
Summary: lib components for the pypi-scikit_image package.
Group: Libraries
Requires: pypi-scikit_image-license = %{version}-%{release}
Requires: pypi-scikit_image-filemap = %{version}-%{release}

%description lib
lib components for the pypi-scikit_image package.


%package license
Summary: license components for the pypi-scikit_image package.
Group: Default

%description license
license components for the pypi-scikit_image package.


%package python
Summary: python components for the pypi-scikit_image package.
Group: Default
Requires: pypi-scikit_image-python3 = %{version}-%{release}

%description python
python components for the pypi-scikit_image package.


%package python3
Summary: python3 components for the pypi-scikit_image package.
Group: Default
Requires: pypi-scikit_image-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(scikit_image)
Requires: pypi(imageio)
Requires: pypi(lazy_loader)
Requires: pypi(networkx)
Requires: pypi(numpy)
Requires: pypi(packaging)
Requires: pypi(pillow)
Requires: pypi(pywavelets)
Requires: pypi(scipy)
Requires: pypi(tifffile)

%description python3
python3 components for the pypi-scikit_image package.


%prep
%setup -q -n scikit_image-0.20.0
cd %{_builddir}/scikit_image-0.20.0
pushd ..
cp -a scikit_image-0.20.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678730523
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
#make test

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-scikit_image
cp %{_builddir}/scikit_image-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-scikit_image/cc0ef2d02f24374cc9874ab696e87aa6d2dbd6fd || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-scikit_image

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-scikit_image/cc0ef2d02f24374cc9874ab696e87aa6d2dbd6fd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
